---
 - include: ../../service_tasks.yml ss={{service}} extra_opts=''

 - name: Create liferay database and user if needed
   command: create-db {{db.name}} {{db.user}} {{db.pass}}

 - name: Start liferay service
   service: name=liferay state=started

