---
- hosts: liferay
  gather_facts: yes
  user: root

  vars:

  roles:
    - { role: base,           tags: base }
    - { role: docker.ubuntu,  tags: docker }
    - { role: docker_mysql,   tags: mysql }
    - { role: docker_liferay, tags: liferay }

